title: Hotkey Help
description: Get things done faster with hotkeys and text expansion
show_downloads: true

theme: jekyll-theme-shoreline-docs

sass:
  sass_dir:         _sass
  style:            :compressed

markdown: kramdown
#gems: [bootstrap, autoprefixer-rails, jekyll-assets, jekyll-paginate, jekyll-gist]
