source 'https://rubygems.org'

gem 'github-pages', group: :jekyll_plugins

gem 'minima'

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-gist'
  gem 'bootstrap', '~> 4.0.0.alpha3'
  gem 'autoprefixer-rails'
  gem 'jekyll-assets'
end
